***

# **EDD Data Testing**

***

EDD contains 19 datasets you can use for California employment data. Years contained are from 1990-2024 for the [CES Survey](https://data.ca.gov/dataset/current-employment-statistics-ces-2). From the previous collection done by SACOG, the data appears to be in a yearly format by industry. The data was collected on Sacramento--Roseville--Arden-Arcade MSA, and Yuba County MSA. Let us try to aggregate by year and see if our results match the previous version.

In [1]:
# Packages

import pandas as pd
import json
import requests
import os
from tqdm import tqdm

In [13]:
# Importing data

path = "C:\\Users\\jchoy\\Documents\\ces_1990-2001_monthly_2024627.csv"

df_edd = pd.read_csv(path)

df_edd.head(3)

,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted (Y/N),Current Employment
0,County,Alameda County,1990,January,01/1/1990,55000000,Financial Activities,N,30400
1,County,Alameda County,1990,January,01/1/1990,11000000,Total Farm,N,1300
2,County,Alameda County,1990,January,01/1/1990,7000000,Service-Providing,N,480700

In [18]:
# Filtering and then merging

df_edd = df_edd[df_edd["Seasonally Adjusted (Y/N)"] == 'N']

df_edd = df_edd[df_edd["Area Name"].isin(['Sacramento--Roseville--Arden-Arcade MSA'])]

df_edd.head(3)

,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted (Y/N),Current Employment
2906,Metropolitan Area,Sacramento--Roseville--Arden-Arcade MSA,1990,January,01/1/1990,20238000,Specialty Trade Contractors,N,21900
2907,Metropolitan Area,Sacramento--Roseville--Arden-Arcade MSA,1990,January,01/1/1990,20238100,"Foundation, Structure, and Buildin...",N,4800
2908,Metropolitan Area,Sacramento--Roseville--Arden-Arcade MSA,1990,January,01/1/1990,20238200,Building Equipment Contractors,N,7800

In [23]:
# Looking at the first year for Sac to compare

df_ninety = df_edd[df_edd['Industry Title'] == 'Total Farm'].head(12)

df_ninety['Current Employment'].sum()

105600

This value of 105,600 is not the same as the one given by the two dataframes (127,400). So perhaps it's a different dataframe?