*** 

# **Rapid API Testing**

***

RapidAPI has a ton of APIs on the marketplace that users can provide. It makes it pretty easy to do quick pulls; you're able to upload all of the parameters you're looking for into the browser and it will provide the code you should paste into your IDE. The pulls aren't always going to be the same dictionary format, so kind of difficult to make a function that will make a good looking dataframe. Currently, I just copy paste the output and subset from there. RapidAPI also has a lot of APIs that require the user to put there card info in, even if it is under the basic free plan. I didn't do any of those ones, just the ones that I didn't have to put my card info in.

In [47]:
import pandas as pd
from geopy.geocoders import Nominatim
import geopandas
from geopy.exc import GeocoderTimedOut
import folium
import requests

***

## **[EV Charger API](https://rapidapi.com/letscrape-6bRBa3QguO5/api/ev-charge-finder)**

***

In [46]:
city_list = ['Sacramento', 'Yuba City', 'Sutter', 'Placerville', 'Davis']

city_list[0] + ', CA, USA'

'Sacramento, CA, USA'

In [57]:
city_list = ['Sacramento', 'Yuba City', 'Sutter', 'Placerville', 'Davis']

for city in city_list:
    querystring = {"near": city + ', CA, USA', "limit":"150"}
    print(querystring)

{'near': 'Sacramento, CA, USA', 'limit': '150'}
{'near': 'Yuba City, CA, USA', 'limit': '150'}
{'near': 'Sutter, CA, USA', 'limit': '150'}
{'near': 'Placerville, CA, USA', 'limit': '150'}
{'near': 'Davis, CA, USA', 'limit': '150'}

In [51]:
url = "https://ev-charge-finder.p.rapidapi.com/search-by-location"

headers = {
	"x-rapidapi-key": "27e65b7c6fmsh305b51f3aade8c3p1fab15jsn7eb2f3787331",
	"x-rapidapi-host": "ev-charge-finder.p.rapidapi.com"
}

city_list = ['Sacramento', 'Yuba City', 'Sutter', 'Placerville', 'Davis']
dfs = []
for city in city_list:
    querystring = {"near": city + ', CA, USA', "limit": "150"}
    response = requests.get(url, headers=headers, params=querystring)

    # Flatten the dictionary
    
    flattened_data = []
    for entry in response.json()['data']:
        flattened_entry = {}
        for key, value in entry.items():
            if isinstance(value, dict):
                for sub_key, sub_value in value.items():
                    flattened_entry[f"{key}_{sub_key}"] = sub_value
            else:
                flattened_entry[key] = value
        flattened_data.append(flattened_entry)

    # Convert to df and append to list

    df = pd.DataFrame(flattened_data)
    dfs.append(df)

# Combine all DataFrames into one

combined_df = pd.concat(dfs, ignore_index=True)

# Display the combined DataFrame

print(combined_df.head())

                                      id                                name  \
0  0x809ad15b8cbba1c5:0xa2589521cfcf7cb4               EVgo Charging Station
1  0x809ad092ad147627:0xad63c9d56852f90e  Electrify America Charging Station
2  0x809ad0d9891631bd:0xc4d5edca25a34faf  Electrify America Charging Station
3  0x809ad19f8e485b4f:0xd4c60fa8998ece30                  Tesla Supercharger
4  0x809ad155319eef91:0x368bf71d3e44c948  Electrify America Charging Station

                                          connectors  \
0  [{'type': 'CCS', 'total': 3, 'available': 0, '...
1  [{'type': 'CCS', 'total': 5, 'available': None...
2  [{'type': 'CCS', 'total': 7, 'available': None...
3  [{'type': 'Tesla', 'total': 20, 'available': N...
4  [{'type': 'CCS', 'total': 11, 'available': Non...

                                   formatted_address  \
0                  2115 6th St, Sacramento, CA 95818
1           1651 Alhambra Blvd, Sacramento, CA 95816
2                    1601 L St, Sacramento, CA 95814
3                               Sacramento, CA 95814
4  Broadway &, 2505 Riverside Blvd EB, Sacramento...

  address_components_district   address_components_street_address  \
0              Southside Park                         2115 6th St
1             East Sacramento                  1651 Alhambra Blvd
2                     Midtown                           1601 L St
3                    Downtown                                None
4                   Land Park  Broadway &, 2505 Riverside Blvd EB

  address_components_city address_components_zipcode address_components_state  \
0              Sacramento                      95818               California
1              Sacramento                      95816               California
2              Sacramento                      95814               California
3              Sacramento                      95814               California
4              Sacramento                      95818               California

  address_components_country  ...  opening_hours_Friday  \
0                         US  ...       [Open 24 hours]
1                         US  ...       [Open 24 hours]
2                         US  ...       [Open 24 hours]
3                         US  ...       [Open 24 hours]
4                         US  ...       [Open 24 hours]

   opening_hours_Saturday opening_hours_Sunday opening_hours_Monday rating  \
0         [Open 24 hours]      [Open 24 hours]      [Open 24 hours]    3.9
1         [Open 24 hours]      [Open 24 hours]      [Open 24 hours]    3.6
2         [Open 24 hours]      [Open 24 hours]      [Open 24 hours]    3.2
3         [Open 24 hours]      [Open 24 hours]      [Open 24 hours]    2.6
4         [Open 24 hours]      [Open 24 hours]      [Open 24 hours]    3.2

  review_count                                            website  \
0           55                               https://www.evgo.com
1            8                   https://www.electrifyamerica.com
2            9  https://www.electrifyamerica.com/locate-charge...
3          123  https://www.tesla.com/findus/location/supercha...
4           13                   https://www.electrifyamerica.com

                                               photo  \
0  https://lh5.googleusercontent.com/p/AF1QipMGUK...
1  https://streetviewpixels-pa.googleapis.com/v1/...
2  https://lh5.googleusercontent.com/p/AF1QipM42S...
3  https://lh5.googleusercontent.com/p/AF1QipOOir...
4  https://lh5.googleusercontent.com/p/AF1QipOWZB...

               google_place_id            google_cid
0  ChIJxaG7jFvRmoARtHzPzyGVWKI  11698264004547804340
1  ChIJJ3YUrZLQmoARDvlSaNXJY60  12494051709671373070
2  ChIJvTEWidnQmoARr0-jJcrt1cQ  14183504053943881647
3  ChIJT1tIjp_RmoARMM6OmagPxtQ  15331959198234627632
4  ChIJke-eMVXRmoARSMlEPh33izY   3930506804781697352

[5 rows x 27 columns]

In [58]:
combined_df

,id,name,connectors,formatted_address,address_components_district,address_components_street_address,address_components_city,address_components_zipcode,address_components_state,address_components_country,...,opening_hours_Friday,opening_hours_Saturday,opening_hours_Sunday,opening_hours_Monday,rating,review_count,website,photo,google_place_id,google_cid
0,0x809ad15b8cbba1c5:0xa2589521cfcf7cb4,EVgo Charging Station,"[{'type': 'CCS', 'total': 3, 'available': 0, '...","2115 6th St, Sacramento, CA 95818",Southside Park,2115 6th St,Sacramento,95818,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],3.9,55,https://www.evgo.com,https://lh5.googleusercontent.com/p/AF1QipMGUK...,ChIJxaG7jFvRmoARtHzPzyGVWKI,11698264004547804340
1,0x809ad092ad147627:0xad63c9d56852f90e,Electrify America Charging Station,"[{'type': 'CCS', 'total': 5, 'available': None...","1651 Alhambra Blvd, Sacramento, CA 95816",East Sacramento,1651 Alhambra Blvd,Sacramento,95816,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],3.6,8,https://www.electrifyamerica.com,https://streetviewpixels-pa.googleapis.com/v1/...,ChIJJ3YUrZLQmoARDvlSaNXJY60,12494051709671373070
2,0x809ad0d9891631bd:0xc4d5edca25a34faf,Electrify America Charging Station,"[{'type': 'CCS', 'total': 7, 'available': None...","1601 L St, Sacramento, CA 95814",Midtown,1601 L St,Sacramento,95814,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],3.2,9,https://www.electrifyamerica.com/locate-charge...,https://lh5.googleusercontent.com/p/AF1QipM42S...,ChIJvTEWidnQmoARr0-jJcrt1cQ,14183504053943881647
3,0x809ad19f8e485b4f:0xd4c60fa8998ece30,Tesla Supercharger,"[{'type': 'Tesla', 'total': 20, 'available': N...","Sacramento, CA 95814",Downtown,None,Sacramento,95814,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],2.6,123,https://www.tesla.com/findus/location/supercha...,https://lh5.googleusercontent.com/p/AF1QipOOir...,ChIJT1tIjp_RmoARMM6OmagPxtQ,15331959198234627632
4,0x809ad155319eef91:0x368bf71d3e44c948,Electrify America Charging Station,"[{'type': 'CCS', 'total': 11, 'available': Non...","Broadway &, 2505 Riverside Blvd EB, Sacramento...",Land Park,"Broadway &, 2505 Riverside Blvd EB",Sacramento,95818,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],3.2,13,https://www.electrifyamerica.com,https://lh5.googleusercontent.com/p/AF1QipOWZB...,ChIJke-eMVXRmoARSMlEPh33izY,3930506804781697352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,0x809ad66437c52ead:0x4393ec47553af04,ChargePoint Charging Station,"[{'type': 'J1772', 'total': 2, 'available': 2,...","2880 Gateway Oaks Dr, Sacramento, CA 95833",Metro Center,2880 Gateway Oaks Dr,Sacramento,95833,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],NaN,0,https://na.chargepoint.com/charge_point?id=1:7...,https://streetviewpixels-pa.googleapis.com/v1/...,ChIJrS7FN2TWmoARBK9TdcQ-OQQ,304343463327149828
420,0x809ad6c4560923df:0xa5f51e679834e43e,ChargePoint Charging Station,"[{'type': 'J1772', 'total': 7, 'available': 7,...","400 Jibboom St, Sacramento, CA 95811",None,400 Jibboom St,Sacramento,95811,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],NaN,0,https://na.chargepoint.com/charge_point?id=1:5...,None,ChIJ3yMJVsTWmoARPuQ0mGce9aU,11958497815836288062
421,0x809ad666eb47565d:0xfc0ea26f44e127c3,ChargePoint Charging Station,"[{'type': 'J1772', 'total': 2, 'available': 2,...","2850 Gateway Oaks Dr, Sacramento, CA 95833",Metro Center,2850 Gateway Oaks Dr,Sacramento,95833,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],NaN,0,https://na.chargepoint.com/charge_point?id=1:6...,https://streetviewpixels-pa.googleapis.com/v1/...,ChIJXVZH62bWmoARwyfhRG-iDvw,18162632946012465091
422,0x809ad12de2301af1:0x8dbe0d50519b703d,ChargePoint Charging Station,"[{'type': 'J1772', 'total': 20, 'available': 1...","500 Capitol Mall, Sacramento, CA 95814",Downtown,500 Capitol Mall,Sacramento,95814,California,US,...,[Open 24 hours],[Open 24 hours],[Open 24 hours],[Open 24 hours],NaN,0,https://na.chargepoint.com/charge_point?id=1:1...,https://streetviewpixels-pa.googleapis.com/v1/...,ChIJ8Row4i3RmoARPXCbUVANvo0,10213615643540549693
423,0x8084df8b12c07f87:0x523c3a51e202cb23,Blink Charging Station,"[{'type': 'J1772', 'total': 1, 'available': No...","201 Railroad Ave, Winters, CA 95694",None,201 Railroad Ave,Winters,95694,California,US,...,[Closed],[Closed],[12–12:30 AM],[Closed],1.0,1,https://www.blinkcharging.com,https://streetviewpixels-pa.googleapis.com/v1/...,ChIJh3_AEovfhIARI8sC4lE6PFI,5925675333071325987

In [61]:
# Function to get latitude and longitude

# Needs to use GeoPy library to convert Lat Longs

geolocator = Nominatim(user_agent="Geopy Library")

def get_lat_lon(address):
    try:
        location = geolocator.geocode(address, timeout=10)
        if location:
            return location.latitude, location.longitude
        else:
            return None, None
    except GeocoderTimedOut:
        return get_lat_lon(address)  # Retry if geocoding times out

# Apply the function
combined_df['Latitude'], combined_df['Longitude'] = zip(*combined_df['formatted_address'].apply(get_lat_lon))

In [64]:
combined_df = combined_df.dropna(subset=['Latitude', 'Longitude'])

In [65]:
map_center = [38.5768267, -121.488201]  # SACOG Address
mymap = folium.Map(location=map_center, zoom_start=12)

# Adding the markers on the map

for _, row in combined_df.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=f"<strong>{row['name']}</strong><br>"
              f"Address: {row['formatted_address']}",
        tooltip=row['name']
    ).add_to(mymap)

# Save the map, lowk don't need to do tho

mymap.save("charging_stations_map.html")

In [66]:
mymap

In [68]:
combined_df['address_components_city'].value_counts()

address_components_city
Sacramento         112
Roseville           37
Rocklin             26
Davis               23
Folsom              21
Woodland            20
Auburn              12
Placerville         11
Lincoln             10
Yuba City           10
Grass Valley         9
West Sacramento      9
Marysville           6
Loomis               6
El Dorado Hills      5
Oroville             4
Pollock Pines        4
Williams             4
Dixon                4
Plymouth             4
Oregon House         4
Willows              3
Colusa               2
North San Juan       2
Palermo              2
freedom wy           2
Winters              2
Chico                1
Brooks               1
Orangevale           1
Cameron Park         1
Sutter Creek         1
Granite Bay          1
Amador City          1
Rancho Murieta       1
Name: count, dtype: int64

***

## **[Zillow Walk / Transit / Bike Score](https://rapidapi.com/s.mahmoud97/api/zillow56/playground/apiendpoint_989e1640-d3ad-4c2c-8cf5-aee3d37f6463)**

***

In [96]:
# Sample code from the API page

url = "https://zillow56.p.rapidapi.com/walk_transit_bike_score"

querystring = {"zpid":"20485700"}

headers = {
	"x-rapidapi-key": "27e65b7c6fmsh305b51f3aade8c3p1fab15jsn7eb2f3787331",
	"x-rapidapi-host": "zillow56.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'data': {'property': {'bikeScore': {'bikescore': 73, 'description': 'Very Bikeable'}, 'id': 'UHJvcGVydHk6MjA0ODU3MDA=', 'transitScore': {'description': 'Excellent Transit', 'transit_score': 71, 'ws_link': 'https://www.walkscore.com/score/loc/lat=34.0186/lng=-118.5028/?utm_source=zillow2.com&utm_medium=ts_api&utm_campaign=ts_api'}, 'walkScore': {'description': 'Very Walkable', 'walkscore': 88, 'ws_link': 'https://www.walkscore.com/score/loc/lat=34.01864/lng=-118.502754/?utm_source=zillow2.com&utm_medium=ws_api&utm_campaign=ws_api'}}}}

In [99]:
response.json()['data']

{'property': {'bikeScore': {'bikescore': 73, 'description': 'Very Bikeable'},
  'id': 'UHJvcGVydHk6MjA0ODU3MDA=',
  'transitScore': {'description': 'Excellent Transit',
   'transit_score': 71,
   'ws_link': 'https://www.walkscore.com/score/loc/lat=34.0186/lng=-118.5028/?utm_source=zillow2.com&utm_medium=ts_api&utm_campaign=ts_api'},
  'walkScore': {'description': 'Very Walkable',
   'walkscore': 88,
   'ws_link': 'https://www.walkscore.com/score/loc/lat=34.01864/lng=-118.502754/?utm_source=zillow2.com&utm_medium=ws_api&utm_campaign=ws_api'}}}

In [72]:
data = response.json()['data']

vector_foil = {
    'id': data['property']['id'],
    'bikeScore_score': data['property']['bikeScore']['bikescore'],
    'bikeScore_description': data['property']['bikeScore']['description'],
    'transitScore_score': data['property']['transitScore']['transit_score'],
    'transitScore_description': data['property']['transitScore']['description'],
    'transitScore_ws_link': data['property']['transitScore']['ws_link'],
    'walkScore_score': data['property']['walkScore']['walkscore'],
    'walkScore_description': data['property']['walkScore']['description'],
    'walkScore_ws_link': data['property']['walkScore']['ws_link']
}

In [76]:
walky = pd.DataFrame([vector_foil])

In [77]:
walky

,id,bikeScore_score,bikeScore_description,transitScore_score,transitScore_description,transitScore_ws_link,walkScore_score,walkScore_description,walkScore_ws_link
0,UHJvcGVydHk6MjA0ODU3MDA=,73,Very Bikeable,71,Excellent Transit,https://www.walkscore.com/score/loc/lat=34.018...,88,Very Walkable,https://www.walkscore.com/score/loc/lat=34.018...

If we had a list of Zillow IDs we wanted to test, this could be pretty cool. For now though, don't think this is something that we can really use.

***

## **[Temporal Weather Patterns](https://rapidapi.com/meteostat/api/meteostat/playground/apiendpoint_8d39939d-4661-41fb-a498-1e76b9930d96)**

***

In [78]:
url = "https://meteostat.p.rapidapi.com/point/monthly"

querystring = {"lat":"38.5768267","lon":"-121488201","alt":"43","start":"2020-01-01","end":"2020-12-31"} # this is using sacog addy

headers = {
	"x-rapidapi-key": "27e65b7c6fmsh305b51f3aade8c3p1fab15jsn7eb2f3787331",
	"x-rapidapi-host": "meteostat.p.rapidapi.com"
} 

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'meta': {'generated': '2024-08-29 22:08:57', 'stations': ['72414', 'K3I20', 'KPKB0', 'KCKB0']}, 'data': [{'date': '2020-01-01', 'tavg': 6.3, 'tmin': 1.4, 'tmax': 11.1, 'prcp': 90.0, 'wspd': 9.0, 'pres': 1021.0, 'tsun': None}, {'date': '2020-02-01', 'tavg': 6.4, 'tmin': 1.3, 'tmax': 11.6, 'prcp': 123.0, 'wspd': 9.4, 'pres': 1017.9, 'tsun': None}, {'date': '2020-03-01', 'tavg': 12.4, 'tmin': 6.8, 'tmax': 17.9, 'prcp': 109.0, 'wspd': 9.4, 'pres': 1019.2, 'tsun': None}, {'date': '2020-04-01', 'tavg': 12.8, 'tmin': 6.7, 'tmax': 18.9, 'prcp': 150.0, 'wspd': 9.6, 'pres': 1013.2, 'tsun': None}, {'date': '2020-05-01', 'tavg': 17.8, 'tmin': 12.1, 'tmax': 23.6, 'prcp': 227.0, 'wspd': 7.6, 'pres': 1016.7, 'tsun': None}, {'date': '2020-06-01', 'tavg': 23.7, 'tmin': 17.9, 'tmax': 29.5, 'prcp': 91.0, 'wspd': 6.3, 'pres': 1016.2, 'tsun': None}, {'date': '2020-07-01', 'tavg': 28.0, 'tmin': 21.8, 'tmax': 34.2, 'prcp': 83.0, 'wspd': 5.2, 'pres': 1015.0, 'tsun': None}, {'date': '2020-08-01', 'tavg': 25.9, 'tmin': 20.2, 'tmax': 31.6, 'prcp': 98.0, 'wspd': 5.3, 'pres': 1014.9, 'tsun': None}, {'date': '2020-09-01', 'tavg': 21.3, 'tmin': 15.5, 'tmax': 27.1, 'prcp': 49.0, 'wspd': 5.6, 'pres': 1018.4, 'tsun': None}, {'date': '2020-10-01', 'tavg': 15.9, 'tmin': 9.7, 'tmax': 22.0, 'prcp': 82.0, 'wspd': 5.3, 'pres': 1018.8, 'tsun': None}, {'date': '2020-11-01', 'tavg': 11.8, 'tmin': 5.0, 'tmax': 18.5, 'prcp': 71.0, 'wspd': 7.4, 'pres': 1022.1, 'tsun': None}, {'date': '2020-12-01', 'tavg': 4.5, 'tmin': -0.1, 'tmax': 9.2, 'prcp': 108.0, 'wspd': 8.1, 'pres': 1019.0, 'tsun': None}]}

In [92]:
weather_stats = response.json()

froggy_era = weather_stats['data']

weather_report = pd.DataFrame(froggy_era)

In [93]:
weather_report

          date  tavg  tmin  tmax   prcp  wspd    pres  tsun
0   2020-01-01   6.3   1.4  11.1   90.0   9.0  1021.0  None
1   2020-02-01   6.4   1.3  11.6  123.0   9.4  1017.9  None
2   2020-03-01  12.4   6.8  17.9  109.0   9.4  1019.2  None
3   2020-04-01  12.8   6.7  18.9  150.0   9.6  1013.2  None
4   2020-05-01  17.8  12.1  23.6  227.0   7.6  1016.7  None
5   2020-06-01  23.7  17.9  29.5   91.0   6.3  1016.2  None
6   2020-07-01  28.0  21.8  34.2   83.0   5.2  1015.0  None
7   2020-08-01  25.9  20.2  31.6   98.0   5.3  1014.9  None
8   2020-09-01  21.3  15.5  27.1   49.0   5.6  1018.4  None
9   2020-10-01  15.9   9.7  22.0   82.0   5.3  1018.8  None
10  2020-11-01  11.8   5.0  18.5   71.0   7.4  1022.1  None
11  2020-12-01   4.5  -0.1   9.2  108.0   8.1  1019.0  None

The limit for this is 50 requests/month. I was thinking about maybe trying this on the entire EV charging dataset generated before, but the hardcap kind of counters this. Could maybe do it using the Peer MSAs offices?