***

# **BLS Queries**

***

In this file, we want to try and pull the total number of employment from BLS for different industries. To give some context, the API works by specifying a specific series id, which can be used to pull data from a specific table from BLS. It can also be used to select information from a table, parameters like specific counties or specific industry can be referenced. The survey we are trying to pull from is State and Employment, Hours, and Earnings; which can be found in the following link: https://www.bls.gov/help/hlpforma.htm#EW.

In [1]:
# Packages

import pandas as pd
import json
import requests

In [2]:
# Base URL for API V2
url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'

# API key in config.py which contains: bls_key = 'key'
key = '03688c33d1194462aa72e4e97253b1e7'
key = '?registrationkey={}'.format(key)

# Series stored as a dictionary
series_dict = {
    'LNS14000003': 'White',
    'LNS14000006': 'Black',
    'LNS14000009': 'Hispanic'}

# Start year and end year
dates = ('2008', '2017')

In [3]:
# Specify json as content type to return
headers = {'Content-type': 'application/json'}

# Submit the list of series as data
data = json.dumps({
    "seriesid": list(series_dict.keys()),
    "startyear": dates[0],
    "endyear": dates[1]})

# Post request for the data
p = requests.post(
    '{}{}'.format(url, key),
    headers=headers,
    data=data).json()['Results']['series']

In [6]:
p

[{'seriesID': 'LNS14000003',
  'data': [{'year': '2017',
    'period': 'M12',
    'periodName': 'December',
    'value': '3.7',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M11',
    'periodName': 'November',
    'value': '3.7',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M10',
    'periodName': 'October',
    'value': '3.6',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M09',
    'periodName': 'September',
    'value': '3.7',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M08',
    'periodName': 'August',
    'value': '3.9',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M07',
    'periodName': 'July',
    'value': '3.8',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M06',
    'periodName': 'June',
    'value': '3.8',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M05',
    'periodName': 'May',
    'value': '3.7',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M04',
    'periodName': 'April',
    'value': '3.9',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M03',
    'periodName': 'March',
    'value': '3.8',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M02',
    'periodName': 'February',
    'value': '4.0',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M01',
    'periodName': 'January',
    'value': '4.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M12',
    'periodName': 'December',
    'value': '4.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M11',
    'periodName': 'November',
    'value': '4.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M10',
    'periodName': 'October',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M09',
    'periodName': 'September',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M08',
    'periodName': 'August',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M07',
    'periodName': 'July',
    'value': '4.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M06',
    'periodName': 'June',
    'value': '4.3',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M05',
    'periodName': 'May',
    'value': '4.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M04',
    'periodName': 'April',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M03',
    'periodName': 'March',
    'value': '4.3',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M02',
    'periodName': 'February',
    'value': '4.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M01',
    'periodName': 'January',
    'value': '4.2',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M12',
    'periodName': 'December',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M11',
    'periodName': 'November',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M10',
    'periodName': 'October',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M09',
    'periodName': 'September',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M08',
    'periodName': 'August',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M07',
    'periodName': 'July',
    'value': '4.5',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M06',
    'periodName': 'June',
    'value': '4.6',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M05',
    'periodName': 'May',
    'value': '4.8',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M04',
    'periodName': 'April',
    'value': '4.7',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M03',
    'periodName': 'March',
    'value': '4.8',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M02',
    'periodName': 'February',
    'value': '4.7',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M01',
    'periodName': 'January',
    'value': '4.9',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M12',
    'periodName': 'December',
    'value': '4.7',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M11',
    'periodName': 'November',
    'value': '5.0',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M10',
    'periodName': 'October',
    'value': '4.9',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M09',
    'periodName': 'September',
    'value': '5.1',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M08',
    'periodName': 'August',
    'value': '5.3',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M07',
    'periodName': 'July',
    'value': '5.3',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M06',
    'periodName': 'June',
    'value': '5.3',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M05',
    'periodName': 'May',
    'value': '5.4',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M04',
    'periodName': 'April',
    'value': '5.3',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M03',
    'periodName': 'March',
    'value': '5.8',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M02',
    'periodName': 'February',
    'value': '5.8',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M01',
    'periodName': 'January',
    'value': '5.7',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M12',
    'periodName': 'December',
    'value': '5.9',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M11',
    'periodName': 'November',
    'value': '6.1',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M10',
    'periodName': 'October',
    'value': '6.3',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M09',
    'periodName': 'September',
    'value': '6.3',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M08',
    'periodName': 'August',
    'value': '6.4',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M07',
    'periodName': 'July',
    'value': '6.5',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M06',
    'periodName': 'June',
    'value': '6.6',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M05',
    'periodName': 'May',
    'value': '6.7',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M04',
    'periodName': 'April',
    'value': '6.7',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M03',
    'periodName': 'March',
    'value': '6.7',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M02',
    'periodName': 'February',
    'value': '6.8',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M01',
    'periodName': 'January',
    'value': '7.1',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M12',
    'periodName': 'December',
    'value': '6.9',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M11',
    'periodName': 'November',
    'value': '6.8',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M10',
    'periodName': 'October',
    'value': '6.9',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M09',
    'periodName': 'September',
    'value': '7.0',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M08',
    'periodName': 'August',
    'value': '7.2',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M07',
    'periodName': 'July',
    'value': '7.3',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M06',
    'periodName': 'June',
    'value': '7.3',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M05',
    'periodName': 'May',
    'value': '7.4',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M04',
    'periodName': 'April',
    'value': '7.4',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M03',
    'periodName': 'March',
    'value': '7.3',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M02',
    'periodName': 'February',
    'value': '7.4',
    'footnotes': [{}]},
   {'year': '2012',
    'period': 'M01',
    'periodName': 'January',
    'value': '7.4',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M12',
    'periodName': 'December',
    'value': '7.5',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M11',
    'periodName': 'November',
    'value': '7.7',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M10',
    'periodName': 'October',
    'value': '7.9',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M09',
    'periodName': 'September',
    'value': '7.9',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M08',
    'periodName': 'August',
    'value': '7.9',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M07',
    'periodName': 'July',
    'value': '8.0',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M06',
    'periodName': 'June',
    'value': '8.1',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M05',
    'periodName': 'May',
    'value': '7.9',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M04',
    'periodName': 'April',
    'value': '8.1',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M03',
    'periodName': 'March',
    'value': '8.0',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M02',
    'periodName': 'February',
    'value': '8.1',
    'footnotes': [{}]},
   {'year': '2011',
    'period': 'M01',
    'periodName': 'January',
    'value': '8.1',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M12',
    'periodName': 'December',
    'value': '8.5',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M11',
    'periodName': 'November',
    'value': '8.9',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M10',
    'periodName': 'October',
    'value': '8.6',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M09',
    'periodName': 'September',
    'value': '8.6',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M08',
    'periodName': 'August',
    'value': '8.6',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M07',
    'periodName': 'July',
    'value': '8.5',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M06',
    'periodName': 'June',
    'value': '8.6',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M05',
    'periodName': 'May',
    'value': '8.7',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M04',
    'periodName': 'April',
    'value': '9.0',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M03',
    'periodName': 'March',
    'value': '8.9',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M02',
    'periodName': 'February',
    'value': '8.9',
    'footnotes': [{}]},
   {'year': '2010',
    'period': 'M01',
    'periodName': 'January',
    'value': '8.8',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M12',
    'periodName': 'December',
    'value': '9.0',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M11',
    'periodName': 'November',
    'value': '9.2',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M10',
    'periodName': 'October',
    'value': '9.2',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M09',
    'periodName': 'September',
    'value': '8.9',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M08',
    'periodName': 'August',
    'value': '8.9',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M07',
    'periodName': 'July',
    'value': '8.7',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M06',
    'periodName': 'June',
    'value': '8.7',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M05',
    'periodName': 'May',
    'value': '8.5',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M04',
    'periodName': 'April',
    'value': '8.1',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M03',
    'periodName': 'March',
    'value': '8.0',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M02',
    'periodName': 'February',
    'value': '7.6',
    'footnotes': [{}]},
   {'year': '2009',
    'period': 'M01',
    'periodName': 'January',
    'value': '7.1',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M12',
    'periodName': 'December',
    'value': '6.7',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M11',
    'periodName': 'November',
    'value': '6.2',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M10',
    'periodName': 'October',
    'value': '5.9',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M09',
    'periodName': 'September',
    'value': '5.4',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M08',
    'periodName': 'August',
    'value': '5.4',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M07',
    'periodName': 'July',
    'value': '5.2',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M06',
    'periodName': 'June',
    'value': '5.0',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M05',
    'periodName': 'May',
    'value': '4.8',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M04',
    'periodName': 'April',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M03',
    'periodName': 'March',
    'value': '4.5',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M02',
    'periodName': 'February',
    'value': '4.4',
    'footnotes': [{}]},
   {'year': '2008',
    'period': 'M01',
    'periodName': 'January',
    'value': '4.4',
    'footnotes': [{}]}]},
 {'seriesID': 'LNS14000006',
  'data': [{'year': '2017',
    'period': 'M12',
    'periodName': 'December',
    'value': '6.7',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M11',
    'periodName': 'November',
    'value': '7.5',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M10',
    'periodName': 'October',
    'value': '7.6',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M09',
    'periodName': 'September',
    'value': '7.2',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M08',
    'periodName': 'August',
    'value': '7.7',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M07',
    'periodName': 'July',
    'value': '7.3',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M06',
    'periodName': 'June',
    'value': '6.9',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M05',
    'periodName': 'May',
    'value': '7.7',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M04',
    'periodName': 'April',
    'value': '7.7',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M03',
    'periodName': 'March',
    'value': '7.8',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M02',
    'periodName': 'February',
    'value': '8.0',
    'footnotes': [{}]},
   {'year': '2017',
    'period': 'M01',
    'periodName': 'January',
    'value': '7.5',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M12',
    'periodName': 'December',
    'value': '8.0',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M11',
    'periodName': 'November',
    'value': '8.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M10',
    'periodName': 'October',
    'value': '8.5',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M09',
    'periodName': 'September',
    'value': '8.5',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M08',
    'periodName': 'August',
    'value': '8.0',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M07',
    'periodName': 'July',
    'value': '8.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M06',
    'periodName': 'June',
    'value': '8.7',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M05',
    'periodName': 'May',
    'value': '8.2',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M04',
    'periodName': 'April',
    'value': '8.8',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M03',
    'periodName': 'March',
    'value': '8.9',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M02',
    'periodName': 'February',
    'value': '8.6',
    'footnotes': [{}]},
   {'year': '2016',
    'period': 'M01',
    'periodName': 'January',
    'value': '8.5',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M12',
    'periodName': 'December',
    'value': '8.5',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M11',
    'periodName': 'November',
    'value': '9.4',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M10',
    'periodName': 'October',
    'value': '9.0',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M09',
    'periodName': 'September',
    'value': '9.3',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M08',
    'periodName': 'August',
    'value': '9.4',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M07',
    'periodName': 'July',
    'value': '9.1',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M06',
    'periodName': 'June',
    'value': '9.7',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M05',
    'periodName': 'May',
    'value': '10.3',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M04',
    'periodName': 'April',
    'value': '9.7',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M03',
    'periodName': 'March',
    'value': '9.9',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M02',
    'periodName': 'February',
    'value': '10.1',
    'footnotes': [{}]},
   {'year': '2015',
    'period': 'M01',
    'periodName': 'January',
    'value': '10.3',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M12',
    'periodName': 'December',
    'value': '10.6',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M11',
    'periodName': 'November',
    'value': '10.9',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M10',
    'periodName': 'October',
    'value': '10.6',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M09',
    'periodName': 'September',
    'value': '11.0',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M08',
    'periodName': 'August',
    'value': '11.4',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M07',
    'periodName': 'July',
    'value': '11.6',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M06',
    'periodName': 'June',
    'value': '11.0',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M05',
    'periodName': 'May',
    'value': '11.4',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M04',
    'periodName': 'April',
    'value': '11.6',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M03',
    'periodName': 'March',
    'value': '12.1',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M02',
    'periodName': 'February',
    'value': '11.8',
    'footnotes': [{}]},
   {'year': '2014',
    'period': 'M01',
    'periodName': 'January',
    'value': '12.1',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M12',
    'periodName': 'December',
    'value': '11.9',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M11',
    'periodName': 'November',
    'value': '12.3',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M10',
    'periodName': 'October',
    'value': '12.8',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M09',
    'periodName': 'September',
    'value': '13.0',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M08',
    'periodName': 'August',
    'value': '12.8',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M07',
    'periodName': 'July',
    'value': '12.6',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M06',
    'periodName': 'June',
    'value': '14.2',
    'footnotes': [{}]},
   {'year': '2013',
    'period': 'M05',
    'periodName': 'May',
    'value': '13.4',

In [16]:
p[0]['data'][0]

{'year': '2017',
 'period': 'M12',
 'periodName': 'December',
 'value': '3.7',
 'footnotes': [{}]}

In [7]:
[f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

['2017-12-01',
 '2017-11-01',
 '2017-10-01',
 '2017-09-01',
 '2017-08-01',
 '2017-07-01',
 '2017-06-01',
 '2017-05-01',
 '2017-04-01',
 '2017-03-01',
 '2017-02-01',
 '2017-01-01',
 '2016-12-01',
 '2016-11-01',
 '2016-10-01',
 '2016-09-01',
 '2016-08-01',
 '2016-07-01',
 '2016-06-01',
 '2016-05-01',
 '2016-04-01',
 '2016-03-01',
 '2016-02-01',
 '2016-01-01',
 '2015-12-01',
 '2015-11-01',
 '2015-10-01',
 '2015-09-01',
 '2015-08-01',
 '2015-07-01',
 '2015-06-01',
 '2015-05-01',
 '2015-04-01',
 '2015-03-01',
 '2015-02-01',
 '2015-01-01',
 '2014-12-01',
 '2014-11-01',
 '2014-10-01',
 '2014-09-01',
 '2014-08-01',
 '2014-07-01',
 '2014-06-01',
 '2014-05-01',
 '2014-04-01',
 '2014-03-01',
 '2014-02-01',
 '2014-01-01',
 '2013-12-01',
 '2013-11-01',
 '2013-10-01',
 '2013-09-01',
 '2013-08-01',
 '2013-07-01',
 '2013-06-01',
 '2013-05-01',
 '2013-04-01',
 '2013-03-01',
 '2013-02-01',
 '2013-01-01',
 '2012-12-01',
 '2012-11-01',
 '2012-10-01',
 '2012-09-01',
 '2012-08-01',
 '2012-07-01',
 '2012-06-01',
 '2012-05-01',
 '2012-04-01',
 '2012-03-01',
 '2012-02-01',
 '2012-01-01',
 '2011-12-01',
 '2011-11-01',
 '2011-10-01',
 '2011-09-01',
 '2011-08-01',
 '2011-07-01',
 '2011-06-01',
 '2011-05-01',
 '2011-04-01',
 '2011-03-01',
 '2011-02-01',
 '2011-01-01',
 '2010-12-01',
 '2010-11-01',
 '2010-10-01',
 '2010-09-01',
 '2010-08-01',
 '2010-07-01',
 '2010-06-01',
 '2010-05-01',
 '2010-04-01',
 '2010-03-01',
 '2010-02-01',
 '2010-01-01',
 '2009-12-01',
 '2009-11-01',
 '2009-10-01',
 '2009-09-01',
 '2009-08-01',
 '2009-07-01',
 '2009-06-01',
 '2009-05-01',
 '2009-04-01',
 '2009-03-01',
 '2009-02-01',
 '2009-01-01',
 '2008-12-01',
 '2008-11-01',
 '2008-10-01',
 '2008-09-01',
 '2008-08-01',
 '2008-07-01',
 '2008-06-01',
 '2008-05-01',
 '2008-04-01',
 '2008-03-01',
 '2008-02-01',
 '2008-01-01']

In [17]:
# Date index from first series
date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

# Empty dataframe to fill with values
df = pd.DataFrame()

# Build a pandas series from the API results, p
for s in p:
    df[series_dict[s['seriesID']]] = pd.Series(
        index = pd.to_datetime(date_list),
        data = [i['value'] for i in s['data']]
        ).astype(float).iloc[::-1]

# Show last 5 results
df.tail()

            White  Black  Hispanic
2017-08-01    3.9    7.7       5.1
2017-09-01    3.7    7.2       5.1
2017-10-01    3.6    7.6       5.0
2017-11-01    3.7    7.5       4.9
2017-12-01    3.7    6.7       5.0

In [18]:
# Series stored as a dictionary
series_dict = {
    'LNS12000000': 'Agricultural Total Employment'} # testing a different series ID

# Start year and end year
dates = ('2022', '2024')

# Specify json as content type to return
headers = {'Content-type': 'application/json'}

# Submit the list of series as data
data = json.dumps({
    "seriesid": list(series_dict.keys()),
    "startyear": dates[0],
    "endyear": dates[1]})

# Post request for the data
p = requests.post(
    '{}{}'.format(url, key),
    headers=headers,
    data=data).json()['Results']['series']
# Date index from first series
date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

# Empty dataframe to fill with values
df = pd.DataFrame()

# Build a pandas series from the API results, p
for s in p:
    df[series_dict[s['seriesID']]] = pd.Series(
        index = pd.to_datetime(date_list),
        data = [i['value'] for i in s['data']]
        ).astype(float).iloc[::-1]

# Show last 5 results
df.tail()

            Agricultural Total Employment
2023-11-01                       161866.0
2023-12-01                       161183.0
2024-01-01                       161152.0
2024-02-01                       160968.0
2024-03-01                       161466.0

***

# **Running Pulls on our Counties Using MSA and Construction as Industry**

***

In [ ]:
def bls_query(series_dict, dates, api_key):

    url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'

    key = '?registrationkey={}'.format(api_key)

    # Specify json as content type to return
    headers = {'Content-type': 'application/json'}

    # Submit the list of series as data
    data = json.dumps({
        "seriesid": list(series_dict.keys()),
        "startyear": dates[0],
        "endyear": dates[1]})

    # Post request for the data
    p = requests.post(
        '{}{}'.format(url, key),
        headers=headers,
        data=data).json()['Results']['series']
    
    # Date index from first series
    date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

    global df

    # Empty dataframe to fill with values
    df = pd.DataFrame()

    # Build a pandas series from the API results, p
    for s in p:
        df[series_dict[s['seriesID']]] = pd.Series(
            index = pd.to_datetime(date_list),
            data = [i['value'] for i in s['data']]
            ).astype(float).iloc[::-1]

    return(df)

In [ ]:
# Making Series ID
series_list = []
front = 'SMU06'

industry = '20236000'

type = '01'

# Making a county list for multiple series id creation | In order: Sac + Placer + El Dorado Yolo, Yuba + Sutter,
county_list = ['40900', '49700']
for i in county_list:
    id = front + i + tail + industry + type
    series_list.append(id)

In [ ]:
series_list

In [ ]:
# Make the dictionary

# if do 19780 it works but not for 

# this is the test code that BLS gave
dicto = {
    'SMU19197802023800001': 'Sac, Placer, El D, Yolo'} # testing a different series ID

years = ('2000', '2024')

# Call the func

my_key = '03688c33d1194462aa72e4e97253b1e7'

bls_query(series_dict=dicto, dates=years, api_key=my_key)

In [ ]:
# Make the dictionary

dicto = {
    'SMU064090050010500000001': 'Sac, Placer, El D, Yolo',
    'SMU064970050012023600001': 'Yuba, Sutter'} # testing a different series ID

years = ('2000', '2024')

# Call the func

my_key = '03688c33d1194462aa72e4e97253b1e7'

bls_query(series_dict=dicto, dates=years, api_key=my_key)

We keep returning empty dataframes when we use our counties. If we use the example query ID 'SMU19197802023800001' which selects Specialty Trade Contractors as the industry and Des Moines-West Des Moines, IA we get a dataframe of length 27. When we ran this query with the original county value (19780) substituted for that of Sacramento county, we got length zero for our frame. It's also important to note that even on our successful pull, we only got data spanning from 2022-2024.

In [ ]:
# Using the Same survey but SIC Basis

# Example SeriesID given

# SAS0800002000011 should have data going back to 2000 - 2002

# Supersector code is contained within the industry codes

#ie 20238000 has a 20 in front, which means construction

dicto = {
    'SAS0800002000011': 'Test SeriesID'} # testing a different series ID

years = ('2000', '2024')

# Call the func

my_key = '03688c33d1194462aa72e4e97253b1e7'

bls_query(series_dict=dicto, dates=years, api_key=my_key)

***

## **Trying Peer MSAs**

***

In [ ]:
# Reading in Data

peers = pd.read_excel("Area Codes (1).xlsx", 'Common Groups')

peers.head(13)

In [ ]:
# Subsetting to only keep our peer counties

# Referencing intiial input as well as the excel file

peers = peers.iloc[10:33]

peers.tail()

In [ ]:
# Attempting to do a pull

# This is using the structure of the test code series id in the documentation: 'SMU19197802023800001'

# Call the func

my_key = '03688c33d1194462aa72e4e97253b1e7'

years = ('2000', '2024')

bls_query(series_dict=dictochat, dates=years, api_key=my_key)

# UPDATE: Accidentally used CA Id for all.

### Notes

* Unsure how great this source is, as there is not a ton of records to pull from.

* In my code, need to update it so that each series is returned separately. To further explain, take the example above. The length of values for some counties, are 27 while some are zero.

* Will also need to change the industries. I surmise that some, counties are going to have more data than other i.e big cities.

In [ ]:
# Trying to test bullet point 3

# County is inside the list as well, so should be returning data.

dicto = {
    'SMU06418602023730001': 'San Francisco-Oakland-Berkeley, CA Metro Area'}

In [ ]:
# Going to do multiple queries using different industries

# No Results: 2023800, 20236000, 20237300

# Checking the URL link on browser (https://api.bls.gov/publicAPI/v2/timeseries/data/20237300)

# I get "invalid series for series Series 2023700" whenever I do this.
bls_query(series_dict=dicto, dates=years, api_key=my_key)

In [ ]:
# Loading state names as well 

states = pd.read_excel("state names.xlsx")

In [ ]:
# Need the codes to be 00, 01, etc
states.iloc[0:8, 0] = '0' + states.iloc[0:8, 0].astype(str)

In [ ]:
states.head()
peers.head()

In [ ]:
# make a function to extract state abbreviation  

import us

# Gets just abbrev out of the text string in peers

def extract_state(text):
    return text.split(',')[1].strip()

# Converting abbreviation to full name

def abbr_full(abbr):
    return us.states.lookup(abbr).name


# Getting each ID now using full name 

def get_id(full_state_name):
    row = states[states['state_name'] == full_state_name]
    if not row.empty:
        return row.iloc[0]['state_code']
    else:
        return None
    
peers['full_name'] = peers['Unnamed: 1'].apply(extract_state)

peers['abbr'] = peers['full_name'].str[:2]

peers['full_name'] = peers['abbr'].apply(abbr_full)

peers['State_ID'] = peers['full_name'].apply(get_id)

In [ ]:
# Changing state id to be string

peers['State_ID'] = peers['State_ID'].astype(str)

In [ ]:
# Create a function to make all of these counties into a dictionary

def dict_maker(df):

    # Formula for Series ID = Prefix + SA + State + Area + Industry + DType
    pre = "SMU"
    
    supersector = "20238000"

    data_type = '01'

    # Making set of keys and vals for future dict
    
    keys = []

    # Have to initialize as we can't use 0 in for loop

    # defo a better way

    first_key = pre + '48' + df.iloc[0, 0] + supersector + data_type

    keys.append(first_key)

    # Now empty list for values in the future dict

    vals = []

    first_val = df.iloc[0,1]
    
    vals.append(first_val)

    for i in range(len(df)):

        # Getting each code
        area_code = df.iloc[i, 0]

        state = peers.iloc[i, 3]

        # Making each SeriesID
        series_id = pre + state + area_code + supersector + data_type

        # Adding to the keylist for future dictionary
        keys.append(series_id)

        val = df.iloc[i, 1]

        vals.append(val)

    result = {k: v for k, v in zip(keys, vals)}

    return result
        
dictochat = dict_maker(df = peers)

In [ ]:
dictochat

In [ ]:
# Running with fixed code

bls_query(series_dict=dictochat, dates=years, api_key=my_key)

Same issue as before, but this should be an easy fix. Again, 27 is the max length we've observed. Farthest data I've seen this survey go back is 2014, is this enough?

In [ ]:
#SMU06409009000000001

sac_dict = {
    'SMU06409009000000001': 'Sac, Placer, El D, Yolo'} # testing a different series ID

years = ('2014', '2024')

# Call the func

my_key = '03688c33d1194462aa72e4e97253b1e7'

bls_query(series_dict=sac_dict, dates=years, api_key=my_key)

In [ ]:
# Let's update bls_query() so that we can make it so that each series is uniform and has 120 rows for all

def bls_query_update(series_dict, dates, api_key):

    url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'

    key = '?registrationkey={}'.format(api_key)

    # Specify json as content type to return
    headers = {'Content-type': 'application/json'}

    # Submit the list of series as data
    data = json.dumps({
        "seriesid": list(series_dict.keys()),
        "startyear": dates[0],
        "endyear": dates[1]})

    # Post request for the data
    p = requests.post(
        '{}{}'.format(url, key),
        headers=headers,
        data=data).json()['Results']['series']
    
    # Date index from first series
    date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

    global df

    # Empty dataframe to fill with values
    df = pd.DataFrame()

    # Build a pandas series from the API results, p

    # We want to make all industries consistent, meaning all counties have 120 rows
    for s in p:
        county_name = series_dict[s['seriesID']]
        county_data = {f"{i['year']}-{i['period'][1:]}-01": float(i['value']) if 'value' in i else 0 for i in s['data']}

        df[county_name] = pd.Series(county_data)

    df.index = pd.to_datetime(date_list)

    return(df)

bls_query_update(series_dict=dictochat, dates = (2000, 2024), api_key = my_key)