***

# **BLS Queries**

***

In this file, we want to try and pull the total number of employment from BLS for different industries. To give some context, the API works by specifying a specific series id, which can be used to pull data from a specific table from BLS. It can also be used to select information from a table, parameters like specific counties or specific industry can be referenced. The survey we are trying to pull from is State and Employment, Hours, and Earnings; which can be found in the following link: https://www.bls.gov/help/hlpforma.htm#EW.

In [3]:
# Packages
import pandas as pd
import json
import requests
import os

In [4]:
# Define user
user = os.getlogin()
path_users = os.path.join('C:\\Users', user)

# Set file paths
if user == 'jfontes':
    path_git = os.path.join(path_users, 'Documents', 'Projects', 'Regional-Monitoring', 'Indicator_Gen')
if user == 'jchoy':
    path_git = os.path.join(path_users, 'Documents', 'Python Projects', 'Regional-Monitoring', 'Indicator_Gen')

path_config = os.path.join(path_git, 'config')
path_config_bls = os.path.join(path_git, 'Python Code', 'BLS', 'config')

print(path_git)

C:\Users\jchoy\Documents\Python Projects\Regional-Monitoring\Indicator_Gen

In [5]:
# Set API key
exec(open(os.path.join(path_config_bls, 'api_key.txt')).read())

# Base URL for API V2
url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'

# API key in config.py which contains: bls_key = 'key'
# key = '03688c33d1194462aa72e4e97253b1e7'
key = dict_api[user]
key = '?registrationkey={}'.format(key)

***

### **Testing Blocks (API example from online source)**


***

In [ ]:
# # Series stored as a dictionary (unemployment rate by ethnicity)
# series_dict = {
#     'LNS14000003': 'White',
#     'LNS14000006': 'Black',
#     'LNS14000009': 'Hispanic'}

# # Start year and end year
# dates = ('2008', '2017')

In [ ]:
# # Specify json as content type to return
# headers = {'Content-type': 'application/json'}

# # Submit the list of series as data
# data = json.dumps({
#     "seriesid": list(series_dict.keys()),
#     "startyear": dates[0],
#     "endyear": dates[1]})

# # Post request for the data
# p = requests.post(
#     '{}{}'.format(url, key),
#     headers=headers,
#     data=data).json()['Results']['series']

In [ ]:
# # Date index from first series
# date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

# # Empty dataframe to fill with values
# df = pd.DataFrame()

# # Build a pandas series from the API results, p
# for s in p:
#     df[series_dict[s['seriesID']]] = pd.Series(
#         index = pd.to_datetime(date_list),
#         data = [i['value'] for i in s['data']]
#         ).astype(float).iloc[::-1]

# # Show last 5 results
# df.tail()

In [ ]:
# # Series stored as a dictionary
# series_dict = {
#     # 'LNS12000000': 'Agricultural Total Employment'
#     'SMU48124202023800001': 'Agricultural Total Employment1'
#     , 'SMU06409002023800001': 'Agricultural Total Employment2'
# }

# # Start year and end year
# dates = ('2022', '2024')

# # Specify json as content type to return
# headers = {'Content-type': 'application/json'}

# # Submit the list of series as data
# data = json.dumps({
#     "seriesid" : list(series_dict.keys()),
#     "startyear": dates[0],
#     "endyear"  : dates[1]
# })

# # Post request for the data
# p = requests.post(
#     '{}{}'.format(url, key),
#     headers=headers,
#     data=data).json()['Results']['series']
# # Date index from first series
# date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

# # Empty dataframe to fill with values
# df = pd.DataFrame()

# # Build a pandas series from the API results, p
# for s in p:
#     df[series_dict[s['seriesID']]] = pd.Series(
#         index = pd.to_datetime(date_list),
#         data = [i['value'] for i in s['data']]
#         ).astype(float).iloc[::-1]

# # Show last 5 results
# df.tail()

***

# **Running Pulls on our Counties Using MSA and Construction as Industry**

***

In [ ]:
# def bls_query(series_dict, dates, api_key):

#     url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'

#     key = '?registrationkey={}'.format(api_key)

#     # Specify json as content type to return
#     headers = {'Content-type': 'application/json'}

#     # Submit the list of series as data
#     data = json.dumps({
#         "seriesid": list(series_dict.keys()),
#         "startyear": dates[0],
#         "endyear": dates[1]})

#     # Post request for the data
#     p = requests.post(
#         '{}{}'.format(url, key),
#         headers=headers,
#         data=data).json()['Results']['series']
    
#     # Date index from first series
#     date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

#     global df

#     # Empty dataframe to fill with values
#     df = pd.DataFrame()

#     # Build a pandas series from the API results, p
#     for s in p:
#         df[series_dict[s['seriesID']]] = pd.Series(
#             index = pd.to_datetime(date_list),
#             data = [i['value'] for i in s['data']]
#             ).astype(float).iloc[::-1]

#     return(df)

In [ ]:
# # Making Series ID
# series_list = []
# front = 'SMU06'

# industry = '20236000'

# type = '01'

# # Making a county list for multiple series id creation | In order: Sac + Placer + El Dorado Yolo, Yuba + Sutter,
# county_list = ['40900', '49700']
# for i in county_list:
#     id = front + i + tail + industry + type
#     series_list.append(id)

In [ ]:
# series_list

In [ ]:
# # Make the dictionary

# # if do 19780 it works but not for 

# # this is the test code that BLS gave
# dicto = {
#     'SMU19197802023800001': 'Sac, Placer, El D, Yolo'} # testing a different series ID

# years = ('2000', '2024')

# # Call the func

# my_key = dict_api['josh']

# bls_query(series_dict=dicto, dates=years, api_key=my_key)

In [ ]:
# # Make the dictionary

# dicto = {
#     'SMU064090050010500000001': 'Sac, Placer, El D, Yolo',
#     'SMU064970050012023600001': 'Yuba, Sutter'} # testing a different series ID

# years = ('2000', '2024')

# # Call the func

# my_key = dict_api['josh']

# bls_query(series_dict=dicto, dates=years, api_key=my_key)

We keep returning empty dataframes when we use our counties. If we use the example query ID 'SMU19197802023800001' which selects Specialty Trade Contractors as the industry and Des Moines-West Des Moines, IA we get a dataframe of length 27. When we ran this query with the original county value (19780) substituted for that of Sacramento county, we got length zero for our frame. It's also important to note that even on our successful pull, we only got data spanning from 2022-2024.

In [ ]:
# # Using the Same survey but SIC Basis

# # Example SeriesID given

# # SAS0800002000011 should have data going back to 2000 - 2002

# # Supersector code is contained within the industry codes

# #ie 20238000 has a 20 in front, which means construction

# dicto = {
#     'SAS0800002000011': 'Test SeriesID'} # testing a different series ID

# years = ('2000', '2024')

# # Call the func

# my_key = dict_api['josh']

# bls_query(series_dict=dicto, dates=years, api_key=my_key)

***

## **Trying Peer MSAs**

***

In [ ]:
# # Attempting to do a pull

# # This is using the structure of the test code series id in the documentation: 'SMU19197802023800001'

# # Call the func

# my_key = '03688c33d1194462aa72e4e97253b1e7'

# years = ('2000', '2024')

# bls_query(series_dict=dictochat, dates=years, api_key=my_key)

# # UPDATE: Accidentally used CA Id for all.

### Notes

* Unsure how great this source is, as there is not a ton of records to pull from.

* In my code, need to update it so that each series is returned separately. To further explain, take the example above. The length of values for some counties, are 27 while some are zero.

* Will also need to change the industries. I surmise that some, counties are going to have more data than other i.e big cities.

In [ ]:
# # Trying to test bullet point 3

# # County is inside the list as well, so should be returning data.

# dicto = {
#     'SMU06418602023730001': 'San Francisco-Oakland-Berkeley, CA Metro Area'}

In [ ]:
# # Going to do multiple queries using different industries

# # No Results: 2023800, 20236000, 20237300

# # Checking the URL link on browser (https://api.bls.gov/publicAPI/v2/timeseries/data/20237300)

# # I get "invalid series for series Series 2023700" whenever I do this.
# bls_query(series_dict=dicto, dates=years, api_key=my_key)

In [6]:
# Reading in Data
df_peer_msa = pd.read_excel(os.path.join(path_config_bls, "BLS_State and Area Employment_Series ID Codes.xlsx"), sheet_name = 'BLS_MSA')
df_peer_msa = df_peer_msa[['msa', 'msa_label']]

df_states = pd.read_excel(os.path.join(path_config, "Area Codes.xlsx"), sheet_name = 'MSAcodes', dtype = {'State FIPS': object})
df_peer_msa = df_peer_msa.merge(df_states[['MSA_ID', 'State FIPS']], left_on = 'msa', right_on = 'MSA_ID', how = 'left')
df_peer_msa = df_peer_msa.drop('MSA_ID', axis = 1)
df_peer_msa.head()

     msa                                     msa_label State FIPS
0  12420   Austin-Round Rock-Georgetown, TX Metro Area         48
1  16740  Charlotte-Concord-Gastonia, NC-SC Metro Area         37
2  17140               Cincinnati, OH-KY-IN Metro Area         39
3  17460               Cleveland-Elyria, OH Metro Area         39
4  18140                       Columbus, OH Metro Area         39

In [ ]:
# # make a function to extract state abbreviation  

# import us

# # Gets just abbrev out of the text string in peers

# def extract_state(text):
#     return text.split(',')[1].strip()

# # Converting abbreviation to full name

# def abbr_full(abbr):
#     return us.states.lookup(abbr).name


# # Getting each ID now using full name 

# def get_id(full_state_name):
#     row = states[states['state_name'] == full_state_name]
#     if not row.empty:
#         return row.iloc[0]['state_code']
#     else:
#         return None
    
# peers['full_name'] = peers['msa_label'].apply(extract_state)

# peers['abbr'] = peers['full_name'].str[:2]

# peers['full_name'] = peers['abbr'].apply(abbr_full)

# peers['State_ID'] = peers['full_name'].apply(get_id)

In [ ]:
# # Changing state id to be string

# peers['State_ID'] = peers['State_ID'].astype(str)

In [ ]:
# # Create a function to make all of these counties into a dictionary

# def dict_maker(df):

#     # Formula for Series ID = Prefix + SA + State + Area + Industry + DType
#     pre = "SMU"
    
#     supersector = "20238000" # We can make this be chosen

#     data_type = '01'

#     # Making set of keys and vals for future dict
    
#     keys = []

#     # Have to initialize as we can't use 0 in for loop

#     # defo a better way

#     first_key = pre + '48' + str(df.iloc[0, 0]) + supersector + data_type

#     keys.append(first_key)

#     # Now empty list for values in the future dict

#     vals = []

#     first_val = str(df.iloc[0,1])
    
#     vals.append(first_val)

#     for i in range(len(df)):

#         # Getting each code
#         area_code = str(df.iloc[i, 0])

#         state = str(df.iloc[i, 2])

#         # Making each SeriesID
#         series_id = pre + state + area_code + supersector + data_type

#         # Adding to the keylist for future dictionary
#         keys.append(series_id)

#         val = str(df.iloc[i, 1])

#         vals.append(val)

#     result = {k: v for k, v in zip(keys, vals)}

#     return result
        
# dictochat = dict_maker(df = df_peer_msa)
# dictochat

In [ ]:
# # Running with fixed code

# bls_query(series_dict=dictochat, dates=years, api_key=my_key)

Same issue as before, but this should be an easy fix. Again, 27 is the max length we've observed. Farthest data I've seen this survey go back is 2014, is this enough?

In [ ]:
# #SMU06409009000000001

# sac_dict = {
#     'SMU06409009000000001': 'Sac, Placer, El D, Yolo'} # testing a different series ID

# years = ('2014', '2024')

# # Call the func

# my_key = dict_api['josh']

# bls_query(series_dict=sac_dict, dates=years, api_key=my_key)

In [ ]:
# # Let's update bls_query() so that we can make it so that each series is uniform and has 120 rows for all

# def bls_query_update(series_dict, dates, api_key):

#     url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'

#     key = '?registrationkey={}'.format(api_key)

#     # Specify json as content type to return
#     headers = {'Content-type': 'application/json'}

#     # Submit the list of series as data
#     data = json.dumps({
#         "seriesid": list(series_dict.keys()),
#         "startyear": dates[0],
#         "endyear": dates[1]})

#     # Post request for the data
#     p = requests.post(
#         '{}{}'.format(url, key),
#         headers=headers,
#         data=data).json()['Results']['series']
    
#     # Date index from first series
#     date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

#     global df

#     # Empty dataframe to fill with values
#     df = pd.DataFrame()

#     # Build a pandas series from the API results, p

#     # We want to make all industries consistent, meaning all counties have 120 rows
#     for s in p:
#         county_name = series_dict[s['seriesID']]
#         county_data = {f"{i['year']}-{i['period'][1:]}-01": float(i['value']) if 'value' in i else 0 for i in s['data']}

#         df[county_name] = pd.Series(county_data)

#     df.index = pd.to_datetime(date_list)

#     return(df)

# bls_query_update(series_dict=dictochat, dates = (2000, 2024), api_key = my_key)

***

## **Pulling All Subsectors With All Peers**

***

In [30]:
# Create a function to make all of these counties into a dictionary

def dict_maker(df, sector):
    """
    Given the file: BLS_State and Area Employment_Series ID Codes.xlsx under the BLS_MSA sheet, we can create a dictionary of 
    all of the MSA counties we want to test. Provide the sector (industry) that you want to pull, and the function will
    return a dictionary of all the MSA series ids formatted for API usage. We must define the first series ID manually,
    but the rest is automated (probably a better way to do it).
    """

    # Formula for Series ID = Prefix + SA + State + Area + Industry + DType
    pre = "SMU"    
    data_type = '01'

    # Making set of keys and vals for future dict
    keys = []
    # Have to initialize as we can't use 0 in for loop

    # defo a better way
    first_key = pre + '48' + str(df.iloc[0, 0]) + sector + data_type
    keys.append(first_key)

    # Now empty list for values in the future dict
    vals = []

    first_val = str(df.iloc[0,1])
    vals.append(first_val)

    for i in range(len(df)):

        # Getting each code
        area_code = str(df.iloc[i, 0])
        state     = str(df.iloc[i, 2])

        # Making each SeriesID
        series_id = pre + state + area_code + sector + data_type

        # Adding to the keylist for future dictionary
        keys.append(series_id)

        val = str(df.iloc[i, 1])

        vals.append(val)

    result = {k: v for k, v in zip(keys, vals)}

    return result
        
dictochat = dict_maker(df = df_peer_msa, sector = '20238000')
dictochat

{'SMU48124202023800001': 'Austin-Round Rock-Georgetown, TX Metro Area',
 'SMU37167402023800001': 'Charlotte-Concord-Gastonia, NC-SC Metro Area',
 'SMU39171402023800001': 'Cincinnati, OH-KY-IN Metro Area',
 'SMU39174602023800001': 'Cleveland-Elyria, OH Metro Area',
 'SMU39181402023800001': 'Columbus, OH Metro Area',
 'SMU26198202023800001': 'Detroit-Warren-Dearborn, MI Metro Area',
 'SMU18269002023800001': 'Indianapolis-Carmel-Anderson, IN Metro Area',
 'SMU29281402023800001': 'Kansas City, MO-KS Metro Area',
 'SMU12331002023800001': 'Miami-Fort Lauderdale-Pompano Beach, FL Metro Area',
 'SMU12367402023800001': 'Orlando-Kissimmee-Sanford, FL Metro Area',
 'SMU04380602023800001': 'Phoenix-Mesa-Chandler, AZ Metro Area',
 'SMU42383002023800001': 'Pittsburgh, PA Metro Area',
 'SMU41389002023800001': 'Portland-Vancouver-Hillsboro, OR-WA Metro Area',
 'SMU06401402023800001': 'Riverside-San Bernardino-Ontario, CA Metro Area',
 'SMU06409002023800001': 'Sacramento-Roseville-Folsom, CA Metro Area',
 'SMU29411802023800001': 'St. Louis, MO-IL Metro Area',
 'SMU49416202023800001': 'Salt Lake City, UT Metro Area',
 'SMU48417002023800001': 'San Antonio-New Braunfels, TX Metro Area',
 'SMU06417402023800001': 'San Diego-Chula Vista-Carlsbad, CA Metro Area',
 'SMU06418602023800001': 'San Francisco-Oakland-Berkeley, CA Metro Area',
 'SMU06419402023800001': 'San Jose-Sunnyvale-Santa Clara, CA Metro Area',
 'SMU12453002023800001': 'Tampa-St. Petersburg-Clearwater, FL Metro Area',
 'SMU06497002023800001': 'Yuba City, CA Metro Area'}

In [8]:
# Series stored as a dictionary
series_dict = {
    # 'SMU48124202023800001': 'Austin-Round Rock-Georgetown, TX Metro Area',
#  'SMU37167402023800001': 'Charlotte-Concord-Gastonia, NC-SC Metro Area',
#  'SMU39171402023800001': 'Cincinnati, OH-KY-IN Metro Area',
#  'SMU39174602023800001': 'Cleveland-Elyria, OH Metro Area',
#  'SMU39181402023800001': 'Columbus, OH Metro Area',
#  'SMU26198202023800001': 'Detroit-Warren-Dearborn, MI Metro Area',
#  'SMU18269002023800001': 'Indianapolis-Carmel-Anderson, IN Metro Area',
 # 'SMU29281402023800001': 'Kansas City, MO-KS Metro Area', # not working for some reason - maybe differet MSA_ID by year?
#  'SMU12331002023800001': 'Miami-Fort Lauderdale-Pompano Beach, FL Metro Area',
#  'SMU12367402023800001': 'Orlando-Kissimmee-Sanford, FL Metro Area',
#  'SMU04380602023800001': 'Phoenix-Mesa-Chandler, AZ Metro Area',
#  'SMU42383002023800001': 'Pittsburgh, PA Metro Area',
#  'SMU41389002023800001': 'Portland-Vancouver-Hillsboro, OR-WA Metro Area',
#  'SMU06401402023800001': 'Riverside-San Bernardino-Ontario, CA Metro Area',
 'SMU06409002023800001': 'Sacramento-Roseville-Folsom, CA Metro Area',
 # 'SMU29411802023800001': 'St. Louis, MO-IL Metro Area',
#  'SMU49416202023800001': 'Salt Lake City, UT Metro Area',
#  'SMU48417002023800001': 'San Antonio-New Braunfels, TX Metro Area',
#  'SMU06417402023800001': 'San Diego-Chula Vista-Carlsbad, CA Metro Area',
 # 'SMU06418602023800001': 'San Francisco-Oakland-Berkeley, CA Metro Area',
#  'SMU06419402023800001': 'San Jose-Sunnyvale-Santa Clara, CA Metro Area',
#  'SMU12453002023800001': 'Tampa-St. Petersburg-Clearwater, FL Metro Area',
#  'SMU06497002023800001': 'Yuba City, CA Metro Area'
}

url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'
key = '?registrationkey={}'.format(dict_api[user])

# Start year and end year
dates = ('2000', '2024')

# Specify json as content type to return
headers = {'Content-type': 'application/json'}

# Submit the list of series as data
data = json.dumps({
    "seriesid" : list(series_dict.keys()),
    "startyear": dates[0],
    "endyear"  : dates[1]
})

# Post request for the data
p = requests.post(
    '{}{}'.format(url, key),
    headers=headers,
    data=data).json()['Results']['series']
# Date index from first series
date_list = [f"{i['year']}-{i['period'][1:]}-01" for i in p[0]['data']]

# Empty dataframe to fill with values
df = pd.DataFrame()

# Build a pandas series from the API results, p
for s in p:
    df[series_dict[s['seriesID']]] = pd.Series(
        index = pd.to_datetime(date_list),
        data = [i['value'] for i in s['data']]
        ).astype(float).iloc[::-1]

# Show last 5 results
df.tail()

            Sacramento-Roseville-Folsom, CA Metro Area
2009-08-01                                        28.5
2009-09-01                                        27.9
2009-10-01                                        27.7
2009-11-01                                        27.2
2009-12-01                                        25.9

In [9]:
# Using this series for testing

series_dict = {
    'SMU48124202023800001': 'Austin-Round Rock-Georgetown, TX Metro Area',
 'SMU37167402023800001': 'Charlotte-Concord-Gastonia, NC-SC Metro Area',
#  'SMU39171402023800001': 'Cincinnati, OH-KY-IN Metro Area',
#  'SMU39174602023800001': 'Cleveland-Elyria, OH Metro Area',
#  'SMU39181402023800001': 'Columbus, OH Metro Area',
#  'SMU26198202023800001': 'Detroit-Warren-Dearborn, MI Metro Area',
#  'SMU18269002023800001': 'Indianapolis-Carmel-Anderson, IN Metro Area',
 # 'SMU29281402023800001': 'Kansas City, MO-KS Metro Area', # not working for some reason - maybe differet MSA_ID by year?
#  'SMU12331002023800001': 'Miami-Fort Lauderdale-Pompano Beach, FL Metro Area',
#  'SMU12367402023800001': 'Orlando-Kissimmee-Sanford, FL Metro Area',
#  'SMU04380602023800001': 'Phoenix-Mesa-Chandler, AZ Metro Area',
#  'SMU42383002023800001': 'Pittsburgh, PA Metro Area',
#  'SMU41389002023800001': 'Portland-Vancouver-Hillsboro, OR-WA Metro Area',
#  'SMU06401402023800001': 'Riverside-San Bernardino-Ontario, CA Metro Area',
 'SMU06409002023800001': 'Sacramento-Roseville-Folsom, CA Metro Area',
 # 'SMU29411802023800001': 'St. Louis, MO-IL Metro Area',
#  'SMU49416202023800001': 'Salt Lake City, UT Metro Area',
#  'SMU48417002023800001': 'San Antonio-New Braunfels, TX Metro Area',
#  'SMU06417402023800001': 'San Diego-Chula Vista-Carlsbad, CA Metro Area',
 # 'SMU06418602023800001': 'San Francisco-Oakland-Berkeley, CA Metro Area',
 'SMU06419402023800001': 'San Jose-Sunnyvale-Santa Clara, CA Metro Area',
 'SMU12453002023800001': 'Tampa-St. Petersburg-Clearwater, FL Metro Area',
 'SMU06497002023800001': 'Yuba City, CA Metro Area'
}

In [14]:
# Need to update bls_query() so that it doesn't only do the first 10 years

# Let's update bls_query() so that we can make it so that each series is uniform and has 120 rows for all

def bls_query_update(series_dict, dates, api_key):
    """ 
    This function takes a dictionary of series, and a series of dates in the form dates = (start, year) to return
    a dataframe with information regarding employment in the sector that the user prescribes. Because of BLS's 
    query limit of up to 10 years of data being pulled at a time for each series ID, the function loops over a set of 10 or less.
    Meaning that if you supply it with years 2000-2024, it will loop three times subsetting between 2000-2009, 2010-2019, 2020-2024.
    It can also work in year ranges less than 10, so if you want to just pull say 2020-2024, that is totally viable.  
    """

    url = 'https://api.bls.gov/publicAPI/v2/timeseries/data/'
    key = '?registrationkey={}'.format(api_key)

    # Specify json as content type to return
    headers = {'Content-type': 'application/json'}

    # Initialize an empty dataframe to store our query results
    df = pd.DataFrame()

    # Queries ten years at once
    year_step = 10

    # Loop through the specified range of years in step intervals
    for year_range_start in range(dates[0], dates[1] + 1, year_step):
        year_range_end = min(year_range_start + year_step - 1, dates[1])

        # Used a print statement for troubleshooting
        # print("Querying data for years {}-{}".format(year_range_start, year_range_end))

        # Submit the request for the current date range
        data = json.dumps({
            "seriesid": list(series_dict.keys()),
            "startyear": year_range_start,
            "endyear": year_range_end})
        response = requests.post('{}{}'.format(url, key), headers=headers, data=data).json()

        # Extract data from the response and append it to the dataframe
        if 'Results' in response and 'series' in response['Results']:
            for series_data in response['Results']['series']:
                series_id = series_data['seriesID']
                if series_id in series_dict:
                    county_name = series_dict[series_id]
                    county_data = {f"{i['year']}-{i['period'][1:]}-01": float(i['value']) if 'value' in i else None for i in series_data['data']}
                    temp_df = pd.DataFrame(index=pd.to_datetime(list(county_data.keys())))
                    temp_df[county_name] = pd.Series(list(county_data.values()), index=temp_df.index)

                    # Concatenate the dataframe to store all of the different years we're testing
                    df = pd.concat([df, temp_df], axis=1)

    return df


# Now, it should return a single dataframe for a single subsector.

# This frame should contain all of the counties, with dates from 2000-2024.

# Additionally, if a county doesn't have data for a specific month, that cell should be empty

bls_query_update(series_dict=series_dict, dates = (2022, 2024), api_key = dict_api[user])

Querying data for years 2022-2024

,"Austin-Round Rock-Georgetown, TX Metro Area","Charlotte-Concord-Gastonia, NC-SC Metro Area","Sacramento-Roseville-Folsom, CA Metro Area","San Jose-Sunnyvale-Santa Clara, CA Metro Area","Tampa-St. Petersburg-Clearwater, FL Metro Area","Yuba City, CA Metro Area"
2024-03-01,48.6,49.3,53.3,37.9,61.3,NaN
2024-02-01,48.4,49.0,52.7,37.3,60.9,NaN
2024-01-01,48.0,48.6,51.4,37.7,60.3,NaN
2023-12-01,49.3,49.1,53.1,39.3,62.0,NaN
2023-11-01,49.4,50.1,54.2,39.8,61.8,NaN
2023-10-01,48.7,49.8,54.2,39.8,61.1,NaN
2023-09-01,48.2,50.1,53.8,39.7,61.0,NaN
2023-08-01,47.5,50.3,53.6,39.7,61.2,NaN
2023-07-01,47.1,50.4,52.9,39.3,60.8,NaN
2023-06-01,47.2,50.7,52.5,39.0,60.9,NaN
2023-05-01,46.3,50.0,51.4,38.6,60.7,NaN
2023-04-01,45.9,49.7,50.1,38.3,60.8,NaN
2023-03-01,45.4,49.7,48.9,38.0,60.5,NaN
2023-02-01,45.0,49.1,49.9,38.6,60.1,NaN
2023-01-01,44.4,48.6,47.2,36.9,59.2,NaN
2022-12-01,45.0,48.2,51.4,38.9,59.2,NaN
2022-11-01,44.9,48.1,52.6,39.3,58.8,NaN
2022-10-01,45.2,48.2,54.0,39.6,58.9,NaN
2022-09-01,45.6,48.2,54.6,39.0,58.6,NaN
2022-08-01,45.6,48.3,54.9,39.2,58.8,NaN
2022-07-01,45.8,48.4,55.4,39.2,58.7,NaN
2022-06-01,46.6,48.8,55.1,39.4,58.5,NaN
2022-05-01,46.1,48.5,55.1,39.0,58.4,NaN
2022-04-01,46.1,48.2,54.0,38.8,58.6,NaN
2022-03-01,45.6,48.1,53.5,37.6,58.3,NaN
2022-02-01,45.3,47.6,53.0,37.3,58.2,NaN
2022-01-01,44.5,47.2,51.2,36.3,57.4,NaN

In [15]:
# Confirming it gets even 2023 data using SMU06409000000000001

sac_dict = {'SMU06409009000000001': 'Sac, Placer, El D, Yolo'}

sac = bls_query_update(series_dict=sac_dict, dates = (2022, 2024), api_key = dict_api[user])

Querying data for years 2022-2024

In [16]:
sac

            Sac, Placer, El D, Yolo
2024-03-01                    264.9
2024-02-01                    262.1
2024-01-01                    261.5
2023-12-01                    261.1
2023-11-01                    262.0
2023-10-01                    258.9
2023-09-01                    255.1
2023-08-01                    252.3
2023-07-01                    249.1
2023-06-01                    260.2
2023-05-01                    260.1
2023-04-01                    256.6
2023-03-01                    256.0
2023-02-01                    252.7
2023-01-01                    251.7
2022-12-01                    252.5
2022-11-01                    253.0
2022-10-01                    247.5
2022-09-01                    244.7
2022-08-01                    242.5
2022-07-01                    239.5
2022-06-01                    248.7
2022-05-01                    249.4
2022-04-01                    248.1
2022-03-01                    247.2
2022-02-01                    244.0
2022-01-01                    245.0

In [17]:
# Now let's run the final function

# Should also try and make it so that you can choose what counties you want.

# This will be done when we make the function in tandem with excel

def full_bls(sector_list, df, date_range, key):

    """
    This function combines the dict_maker() and bls_query_update() to make a set of Series IDs for multiple MSAs, sectors, and year range, all
    defined by user. We then return the data in a set of dfs, separated by industry in the sector list. Meaning, df[0] will contain information
    only for the first sector in the sector list. 
    """
    
    # Initialize an empty list so we can iterate over multiple dictionaries
    sector_chamber = []

    # Initialize empty list for each dataframe we will end up making
    df_chamber = []

    # Loop over each sector we want to test
    for i in sector_list:
        sector_chamber.append(dict_maker(df, i))

    # Now with the sector_holders list containing each set of series we want, we can run our query function iteratively
    
    # Iteratively make each dataframe
    for sector_dict in sector_chamber:
        df_chamber.append(bls_query_update(sector_dict, date_range, api_key = key))

    return(df_chamber)
# Perhaps we can multiprocess this. For loops very bad for efficiency, and this is going to be a p lengthy process.

In [ ]:
import multiprocessing
import time

# This is a multiprocess function for improved efficiency.
def full_bls(sector_list, df, key):

    # Empty list to store results
    results = []

    # Define a function to process each sector, use time for rate limit
    def process_sector(sector):
        time.sleep(10)
        return bls_query_update(dict_maker(df, sector), dates=(2000, 2024), api_key=key)

    # Create a pool of worker processes
    with multiprocessing.Pool(processes=multiprocessing.cpu_count()) as pool:
        
        # Map the sectors to worker processes
        results = pool.map(process_sector, sector_list)

    return results

The API returns up to 10 years of data for up to 25 time series. We will have to separate the queries in half, and then stack the frames on top of each other. 

Also, we can actually pull all the way back to 1990. So maybe we have to do this process three times.

In [18]:
# Testing Agg = Total Nonfarm - Total Priv

sectors = ['00000000', '05000000', '08000000']
dfs = full_bls(sectors, df_peer_msa, date_range = (2000, 2024), dict_api[user])

Querying data for years 2000-2009
Querying data for years 2010-2019
Querying data for years 2020-2024
Querying data for years 2000-2009
Querying data for years 2010-2019
Querying data for years 2020-2024
Querying data for years 2000-2009
Querying data for years 2010-2019
Querying data for years 2020-2024

In [19]:
dfs[0]

,"Austin-Round Rock-Georgetown, TX Metro Area","Charlotte-Concord-Gastonia, NC-SC Metro Area","Cincinnati, OH-KY-IN Metro Area","Cleveland-Elyria, OH Metro Area","Columbus, OH Metro Area","Detroit-Warren-Dearborn, MI Metro Area","Indianapolis-Carmel-Anderson, IN Metro Area","Kansas City, MO-KS Metro Area","Miami-Fort Lauderdale-Pompano Beach, FL Metro Area","Orlando-Kissimmee-Sanford, FL Metro Area",...,"Riverside-San Bernardino-Ontario, CA Metro Area","Sacramento-Roseville-Folsom, CA Metro Area","St. Louis, MO-IL Metro Area","Salt Lake City, UT Metro Area","San Antonio-New Braunfels, TX Metro Area","San Diego-Chula Vista-Carlsbad, CA Metro Area","San Francisco-Oakland-Berkeley, CA Metro Area","San Jose-Sunnyvale-Santa Clara, CA Metro Area","Tampa-St. Petersburg-Clearwater, FL Metro Area","Yuba City, CA Metro Area"
2000-01-01,657.4,912.1,992.4,1113.7,910.1,2159.5,876.5,957.4,2121.3,888.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-02-01,667.0,914.5,998.7,1118.1,916.2,2161.5,883.3,960.5,2134.5,898.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-03-01,674.3,924.9,1008.7,1126.3,922.7,2175.7,893.5,970.6,2153.4,906.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-04-01,675.0,932.1,1012.4,1132.0,929.6,2209.3,895.5,978.0,2152.0,904.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-01,682.4,937.3,1022.2,1144.4,936.6,2236.5,905.4,981.6,2162.9,908.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1713.6,1095.3,1450.3,832.6,1183.5,1570.3,2482.8,1165.0,1559.9,52.4
2023-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1718.5,1095.9,1445.8,830.4,1186.9,1572.0,2490.7,1167.8,1559.6,52.6
2024-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1684.9,1081.6,1416.1,819.0,1167.9,1545.9,2446.0,1147.6,1541.1,51.3
2024-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1686.5,1087.3,1426.3,820.6,1176.7,1552.8,2453.3,1150.0,1552.3,51.2
2024-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1692.3,1092.1,1435.7,822.6,1176.3,1557.2,2460.2,1156.2,1553.2,52.2

In [24]:
# Trying to find agriculture
trade = ['41000000']
trade_df = full_bls(trade, df_peer_msa, dict_api[user])

Querying data for years 2000-2009
Querying data for years 2010-2019
Querying data for years 2020-2024

In [26]:
# This most recent line i ran I think i ran out of queries. 

trade_df[0]

[Empty DataFrame
 Columns: []
 Index: []]

In [27]:
# Let's test this first function

sectors = ['00000000', '10000000', '20000000']
dfs = full_bls(sectors, df_peer_msa, dict_api[user])

Querying data for years 2000-2009
Querying data for years 2010-2019
Querying data for years 2020-2024
Querying data for years 2000-2009
Querying data for years 2010-2019
Querying data for years 2020-2024
Querying data for years 2000-2009
Querying data for years 2010-2019
Querying data for years 2020-2024

In [28]:
# Ran out of queries

print(dfs[0].shape)
print(dfs[1].shape)
print(dfs[2].shape)

(0, 0)
(0, 0)
(0, 0)

In [ ]:
# Testing rows 335 and 339 for Garrett

# Trying to see if these dfs are different given our peer counties
gov_ed = ['90931611', '90936111']
gov_ed_dfs = full_bls(gov_ed, peers, my_key)

In [ ]:
# The test one had data from 2000, 2022

# Diagnosing if my code is correctly looping all the years

gov_ed = ['90931611', '90936111']
gov_ed_dfs = full_bls(gov_ed, peers, my_key)

In [ ]:
display(gov_ed_dfs[0])

In [ ]:
display(gov_ed_dfs[1])

Code graveyard